pipelines:
    branches:
        develop:
            -   step:
                    name: Build and Install
                    image: drud/ddev-webserver:v1.16.1
                    script:
                        - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
                        - git fetch --unshallow
                        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
                        - git fetch origin
                        - git checkout master
                        - git merge -s ours develop --no-commit --no-ff
                        - git checkout develop .
                        - composer install
                        - npm install
                        - rm -rf Tests .editorconfig .gitignore .ddev bitbucket-pipelines.yml composer.lock package.json tsconfig.json webpack.*.js  Gruntfile.js vendor public Build package-lock.json bin node_modules Resources/Private/TypeScript Resources/Private/Scss
                        - git add *
                        - 'git commit -a -m "build: $BITBUCKET_COMMIT_SHORT" --allow-empty'
                        - git push origin master --tags
